# Generated by Django 3.1.4 on 2020-12-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
    ]
