# Generated by Django 3.1.4 on 2020-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20201213_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
